### ISSUE TITLE
[bug] Chat spamming

### ISSUE THREAD

**Issue by menkzy** [qbcore-framework/qb-menu#25]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
Since the newest update, when you use qb-target qb-menu will spam your chat with a command.

**To Reproduce**
Update qb-core, qb-menu & qb-target 
Open your "third eye" / Press alt

**Expected behavior**
Eye shows and nothing happens, OR qb-menu opens and eye does not.

**Screenshots**
https://cdn.discordapp.com/attachments/913661874116132893/959039248214925342/FiveM_b2545_GTAProcess_T2AkrarbaJ.gif

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] yesterday (of this bug report)
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] qb-target qb-menu qb-core latest updates.
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by MrEvilGamer** [comment]
https://github.com/qbcore-framework/qb-menu/compare/main...MrEvilGamer:patch-1

**Comment by MrEvilGamer** [comment]
here's the fix by fishy
