### ISSUE TITLE
New Alphabetical Ordering [BUG]

### ISSUE THREAD

**Issue by 1KingTrill** [qbcore-framework/qb-menu#45]
The new feature to organize menu alphabetically doesn't work with qb-vehicleshop. Whenever you click vehicle interaction, nothing happens. No errors in console either.

**Comment by GodyFromDiscord** [comment]
Can you give context on what you did and the code you used

**Comment by 1KingTrill** [comment]
i didn't mean to close, but i cleared my server cache and it started working but the vehicles are still out of order, do i need to add something specifically to vehicleshop?

**Comment by 1KingTrill** [comment]
> Can you give context on what you did and the code you used

i didn't mean to close, but i cleared my server cache and it started working but the vehicles are still out of order, do i need to add something specifically to vehicleshop?
